### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by gpkash** [bradhilton/SwiftKVC#4]
Any plans to put out a version that supports Swift 3.0?

**Comment by danielebogo** [comment]
+1

**Comment by belozierov** [comment]
Pls, сould you add support for Swift 3, thx

**Comment by inamiy** [comment]
FYI: Updated code for Swift 3 in https://github.com/bradhilton/SwiftKVC/pull/5

**Comment by bradhilton** [comment]
I published a new release, `3.0.0`, which supports Swift 3. Sorry for the delay.
